name: decidim-rspec
description: Decidim module setup (test app generation)
author: mainio
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: ./package-lock.json
    - run: bundle exec rake test_app
      name: Create test app
      shell: "bash"
    - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
      name: Create the screenshots folder
      shell: "bash"
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '115.0.5790.170' # Fix issue: https://github.com/nanasess/setup-chromedriver/issues/200
    - run: RAILS_ENV=test bundle exec rails assets:precompile
      name: Precompile assets
      working-directory: ./spec/decidim_dummy_app/
      shell: "bash"
