name: decidim-rspec
description: Decidim module setup (test app generation)
author: mainio
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: ./package-lock.json
    - uses: actions/cache@v3
      id: decidim-app-cache
      with:
        path: ./spec/decidim_dummy_app/
        key: decidim-app-${{ github.sha }}
        restore-keys: decidim-app-${{ github.sha }}
    - run: bundle exec rake test_app
      name: Create test app
      shell: "bash"
    - run: RAILS_ENV=test bundle exec rails assets:precompile
      name: Precompile assets
      working-directory: ./spec/decidim_dummy_app/
      shell: "bash"
