name: decidim-rspec
description: Decidim module tests (RSpec)
author: mainio
inputs:
  use-cached-app:
    description: Loads the generated test application from the cache also loads the DB schema for the cached app.
    required: false
    default: true
  load-schema:
    description: Loads the DB schema in case the database has not been initialized.
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    # Note that the cache action needs to come after the checkout because it
    # deletes the whole folder.
    - uses: actions/cache@v3
      id: decidim-app-cache
      with:
        path: ./spec/decidim_dummy_app/
        key: decidim-app-${{ github.sha }}
        restore-keys: decidim-app-${{ github.sha }}
      if: ${{ fromJSON(inputs.use-cached-app) }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '115.0.5790.170' # Fix issue: https://github.com/nanasess/setup-chromedriver/issues/200
    - run: bundle exec rails db:schema:load
      name: Load DB schema
      shell: "bash"
      working-directory: ./spec/decidim_dummy_app/
      if: ${{ fromJSON(inputs.use-cached-app) || fromJSON(inputs.load-schema) }}
    - run: bundle exec rspec
      name: RSpec
      shell: "bash"
    - uses: codecov/codecov-action@v3
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: ./spec/decidim_dummy_app/tmp/screenshots
        if-no-files-found: ignore
