name: decidim-rspec
description: Decidim module tests (RSpec)
author: mainio
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '115.0.5790.170' # Fix issue: https://github.com/nanasess/setup-chromedriver/issues/200
    - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
      name: Create the screenshots folder
      shell: "bash"
    - run: bundle exec rspec
      name: RSpec
      shell: "bash"
    - uses: codecov/codecov-action@v3
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: ./spec/decidim_dummy_app/tmp/screenshots
        if-no-files-found: ignore
