name: decidim-rspec
description: Decidim module tests (RSpec)
author: mainio
runs:
  using: composite
  steps:
    - run: bundle exec rspec
      name: RSpec
      shell: "bash"
    - uses: codecov/codecov-action@v3
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: ./spec/decidim_dummy_app/tmp/screenshots
        if-no-files-found: ignore
