on: workflow_call
jobs:
  build_app:
    name: Build app
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/cache@v3
        id: decidim-app-cache
        with:
          path: ./spec/decidim_dummy_app/
          key: decidim-app-${{ github.sha }}
          restore-keys: decidim-app-${{ github.sha }}
      - uses: mainio/gha-decidim-module/setup_app@main
