on: workflow_call
jobs:
  test_js:
    name: Test app (JS)
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - uses: mainio/gha-decidim-module/test_js@main
