on: workflow_call
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - uses: mainio/gha-decidim-module/lint@main
