on:
  workflow_call:
    inputs:
      rubocop:
        description: Enable Rubocop
        required: true
        default: true
        type: boolean
      eslint:
        description: Enable ESLint
        required: true
        default: false
        type: boolean
      stylelint:
        description: Enable Stylelint
        required: true
        default: false
        type: boolean
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - uses: mainio/gha-decidim-module/lint@main
        with:
          rubocop: ${{ inputs.rubocop }}
          eslint: ${{ inputs.eslint }}
          stylelint: ${{ inputs.stylelint }}
